<script setup>
import { computed } from 'vue'
import AppIcon from './AppIcon.vue'
import { phase, phaseLabels, registration, date } from '../lib/contests'
const props = defineProps({ contest: Object, saved: Boolean })
defineEmits(['bookmark'])
const ended = computed(() => phase(props.contest) === 'ended')
function scrollToRegistration() {
  document.getElementById('registration')?.scrollIntoView({ behavior: 'smooth', block: 'start' })
}
</script>

<template>
  <div class="breadcrumb"><a href="#/"><AppIcon name="back" :size="16" />比赛列表</a><span>/</span><span>{{ contest.series }}</span><span>/</span><span>比赛详情</span></div>
  <section class="detail-hero"><div class="row-tags"><span class="series-tag">{{ contest.series }}</span><span class="status" :class="ended ? 'neutral' : 'green'">{{ phaseLabels[phase(contest)] }}</span><span class="demo-tag">演示赛事</span></div><h1>{{ contest.name }}</h1><p>{{ contest.introduction }}</p><div class="hero-meta"><span><AppIcon name="calendar" :size="17" />{{ date(contest.startAt, true) }}</span><span><AppIcon name="users" :size="17" />{{ contest.format }}</span><span><AppIcon name="pin" :size="17" />{{ contest.location }}</span></div></section>
  <div class="detail-layout">
    <div class="detail-main">
      <section class="detail-card"><div class="section-heading"><span>01</span><h2>比赛概览</h2></div><p class="description">{{ contest.description }}</p><dl class="info-grid"><div><dt>参赛对象</dt><dd>{{ contest.eligibility }}</dd></div><div><dt>比赛形式</dt><dd>{{ contest.format }} · {{ contest.mode }}</dd></div><div><dt>比赛时间</dt><dd>{{ date(contest.startAt, true) }}<br v-if="contest.endAt" /><span v-if="contest.endAt">至 {{ date(contest.endAt, true) }}</span></dd></div><div><dt>报名截止</dt><dd>{{ date(contest.registrationDeadline, true) }}</dd></div><div><dt>可用语言</dt><dd>{{ contest.languages.join(' / ') }}</dd></div><div><dt>报名费用</dt><dd>{{ contest.fee }}</dd></div></dl></section>
      <section id="registration" class="detail-card"><div class="section-heading"><span>02</span><h2>{{ ended ? '报名与选拔记录' : '报名与校内选拔' }}</h2></div><div class="inline-notice"><AppIcon name="info" :size="18" /><span>以下为“示例大学”的演示安排，不是实际报名通知。</span></div><div class="selection-heading"><h3>{{ contest.selection.required ? '需要校内选拔' : '无需校内选拔' }}</h3><span class="tag">示例大学</span></div><p class="description">{{ contest.selection.description }}</p><ol class="steps"><li v-for="(step, i) in contest.registrationSteps" :key="step"><span>{{ i + 1 }}</span><p>{{ step }}</p></li></ol><dl class="contact-grid"><div v-if="contest.selection.required"><dt>选拔时间</dt><dd>{{ date(contest.selection.at, true) }}</dd></div><div><dt>校内联系</dt><dd>{{ contest.contact }}</dd></div><div><dt>报名入口</dt><dd>演示数据，暂未提供实际报名链接</dd></div><div v-if="contest.selection.required"><dt>选拔通知</dt><dd>演示数据，暂未提供实际选拔链接</dd></div></dl></section>
      <section class="detail-card"><div class="section-heading"><span>03</span><h2>我适合参加吗？</h2></div><div class="level-panel"><div class="level-score"><strong>{{ contest.difficulty }}<small>/ 10</small></strong><span>参考难度</span></div><div><h3>{{ contest.level }}</h3><p>{{ contest.levelDescription }}</p></div></div><p class="muted small">难度与 CF 建议为演示评价，不是官方门槛，也不代表获奖保证。</p><div class="skill-tags"><span v-for="skill in contest.skills" :key="skill">{{ skill }}</span></div><h3 class="subheading">备赛建议</h3><p class="description">{{ contest.preparation }}</p></section>
      <section class="detail-card"><div class="section-heading"><span>04</span><h2>{{ ended ? '参赛记录与获奖情况' : '历届获奖参考' }}</h2><span class="tag">本校 · 演示统计</span></div><div class="table-wrap"><table><caption class="sr-only">本校历届参赛与获奖统计，单位：{{ contest.teamSize > 1 ? '队' : '人' }}</caption><thead><tr><th>年份</th><th>参赛{{ contest.teamSize > 1 ? '队伍' : '人数' }}</th><th>金 / 一等奖</th><th>银 / 二等奖</th><th>铜 / 三等奖</th></tr></thead><tbody><tr v-for="item in contest.history" :key="item.year"><td>{{ item.year }}</td><td>{{ item.participants }}</td><td>{{ item.gold }}</td><td>{{ item.silver }}</td><td>{{ item.bronze }}</td></tr></tbody></table></div><p class="table-note">统计单位：{{ contest.teamSize > 1 ? '队伍' : '个人' }}；仅展示示例大学数据，各奖项不重复计数。</p><template v-if="ended"><h3 class="subheading">本届参赛{{ contest.teamSize > 1 ? '队伍' : '选手' }}</h3><div v-for="team in contest.results" :key="team.name" class="team-result"><span class="award-icon"><AppIcon name="trophy" :size="20" /></span><div><strong>{{ team.name }}</strong><p>{{ team.members }}</p></div><span class="award-label">{{ team.award }}</span></div><h3 class="subheading">赛场相册</h3><div class="photo-empty"><AppIcon name="photo" :size="28" /><div><strong>等一张属于这场比赛的照片</strong><p>暂无真实照片，后续可收录赛场瞬间与队伍合照。</p></div></div></template></section>
    </div>
    <aside class="detail-sidebar"><section class="action-card"><span class="eyebrow">{{ ended ? 'CONTEST RECAP' : 'MAKE YOUR NEXT MOVE' }}</span><h2>{{ ended ? '比赛已落幕，成长不停。' : '把这场比赛，排进计划。' }}</h2><dl><div><dt>当前状态</dt><dd :class="{ 'green-text': registration(contest) === '报名中' }">{{ registration(contest) }}</dd></div><div><dt>{{ ended ? '比赛日期' : '报名截止' }}</dt><dd>{{ date(ended ? contest.startAt : contest.registrationDeadline) }}</dd></div><div><dt>校内选拔</dt><dd>{{ contest.selection.required ? '需要' : '不需要' }}</dd></div></dl><a v-if="!ended" class="button primary full" href="#registration" @click.prevent="scrollToRegistration">查看报名说明<AppIcon name="arrow" :size="16" /></a><button class="button full" :class="{ 'saved-button': saved }" :aria-pressed="saved" @click="$emit('bookmark')"><AppIcon :name="saved ? 'check' : 'bookmark'" :size="17" />{{ saved ? '已收藏比赛' : '收藏这场比赛' }}</button><p class="small muted">收藏保存在当前浏览器，不会发送通知。</p></section><section class="source-card"><h3><AppIcon name="info" :size="17" />信息说明</h3><p>本页面用于展示产品功能，赛程、费用、能力建议、选拔与成绩均为虚构示例。</p><p>真实参赛前，请通过组委会或学校发布的正式通知确认。</p><span>示例更新于 {{ contest.updatedAt }}</span></section><a href="#/" class="back-list"><AppIcon name="back" :size="16" />继续发现其他比赛</a></aside>
  </div>
</template>

